### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by cloudcoderuwu** [nosix1992/Unreal-Flock-AI-Fish-VR#1]
Hi I was wondering if you had information about how to set up a basic example with your plugin? 

An example project file would suffice.

Thanks!

**Comment by no5ix** [comment]
My pleasure.
Please Check out the latest README.md to follow the "How to use" ^_^

**Comment by cloudcoderuwu** [comment]
Great! Got it working.

The example scene doesn't contain a "FlockAIMoveToLeader" actor however, and adding one doesnt seem to allow the flocking parameters to be changed.

What is the process for that?

**Comment by no5ix** [comment]
1. create a Blueprint class (for example, "TestFishSpawner_BP") based on FlockAISpawner, then place an instance of it in your map, and set its paramaters
2. create a Blueprint class (for example, "TestFishLeader_BP) based on FlockAILeader, then place an instance of it in your map
3. create a Blueprint class (for example, "TestFish_BP") based on FlockAIMoveToLeader, then open TestFish_BP and set its parameters "FlockAI-GeneralConfig-FlockAILeaderClass" to be "TestFishLeader_BP"

**Comment by cloudcoderuwu** [comment]
thanks!
